### PR TITLE
Codeforces

### PR DESCRIPTION
**Pull request by AyushRajSharma**
Added 3 codeforces contest

### CODE REVIEW

**Comment by AyushRajSharma** [comment]
Codeforces_95_1418A

**Comment by AyushRajSharma** [comment]
Codeforces_669_1407A

**Comment by AyushRajSharma** [comment]
Codeforces_674_1426B

**Comment by AyushRajSharma** [comment]
i had already created and uploaded a Readme.md file

**Comment by proRamLOGO** [comment]
These submissions aren't recent.

**Comment by AyushRajSharma** [comment]
These are recent submission you can check out dates and also these are not
ongoing contest.

**Pull request closed without merging**
